apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHRnNXY2dG03
  CLOUDINARY_KEY: NzkzOTM0MzQxNzE1OTkz
  CLOUDINARY_SECRET: NzhJMWY4N2dnMXJyeHJGSk1fczhXdWFZU0FB
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lZV1J0YVc0dGJHOW5hVzRpTENKaElqb2lZMjF0YUhBemJIRnhNR0Z1WXpKdmMyWm5help3Tmpodk1pSjkuRGFXWGVoNkY4T3l6NU1hS3l2SkVoQQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbmRiOmFkbWluQDEyM0BldmVudHMtY2x1c3Rlci5wb2Ruc3VuLm1vbmdvZGIubmV0Lz9hcHBOYW1lPWV2ZW50cy1jbHVzdGVy
